import { CssMapKeys, Spacing, SpacingAliases, ThemeMode } from '@impulse-ui/types';

import { borderTransform, noTransform, spacingTransform } from './transforms';

const LIGHT: ThemeMode = 'light';
const DARK: ThemeMode = 'dark';

const cssPropsMap: Record<CssMapKeys, Function> = {
  alignContent: noTransform,
  alignItems: noTransform,
  alignSelf: noTransform,
  border: borderTransform,
  borderBottom: borderTransform,
  borderLeft: borderTransform,
  borderRadius: noTransform,
  borderRight: borderTransform,
  borderTop: borderTransform,
  bottom: noTransform,
  boxSizing: noTransform,
  columnGap: () => {},
  display: noTransform,
  flex: noTransform,
  flexBasis: () => {},
  flexDirection: () => {},
  flexGrow: () => {},
  flexShrink: () => {},
  flexWrap: () => {},
  fontFamily: () => {},
  fontSize: () => {},
  fontStyle: () => {},
  fontWeight: noTransform,
  gap: () => {},
  gridArea: () => {},
  gridAutoColumns: () => {},
  gridAutoFlow: () => {},
  gridAutoRows: () => {},
  gridColumn: () => {},
  gridRow: () => {},
  gridTemplateAreas: () => {},
  gridTemplateColumns: () => {},
  gridTemplateRows: () => {},
  height: noTransform,
  justifyContent: noTransform,
  justifyItems: noTransform,
  justifySelf: noTransform,
  left: noTransform,
  letterSpacing: () => {},
  lineHeight: noTransform,
  m: spacingTransform,
  margin: noTransform,
  marginBlock: noTransform,
  marginBlockEnd: noTransform,
  marginBlockStart: noTransform,
  marginBottom: noTransform,
  marginInline: noTransform,
  marginInlineEnd: noTransform,
  marginInlineStart: noTransform,
  marginLeft: noTransform,
  marginRight: noTransform,
  marginTop: noTransform,
  marginX: spacingTransform,
  marginY: spacingTransform,
  maxHeight: noTransform,
  maxWidth: noTransform,
  mb: spacingTransform,
  minHeight: noTransform,
  minWidth: noTransform,
  ml: spacingTransform,
  mr: spacingTransform,
  mt: spacingTransform,
  mx: spacingTransform,
  my: spacingTransform,
  order: () => {},
  overflow: noTransform,
  p: spacingTransform,
  padding: noTransform,
  paddingBlock: noTransform,
  paddingBlockEnd: noTransform,
  paddingBlockStart: noTransform,
  paddingBottom: noTransform,
  paddingInline: noTransform,
  paddingInlineEnd: noTransform,
  paddingInlineStart: noTransform,
  paddingLeft: noTransform,
  paddingRight: noTransform,
  paddingTop: noTransform,
  paddingX: spacingTransform,
  paddingY: spacingTransform,
  pb: spacingTransform,
  pl: spacingTransform,
  position: noTransform,
  pr: spacingTransform,
  pt: spacingTransform,
  px: spacingTransform,
  py: spacingTransform,
  right: noTransform,
  rowGap: () => {},
  sizeHeight: () => {},
  sizeWidth: () => {},
  textAlign: () => {},
  textOverflow: () => {},
  textTransform: () => {},
  top: noTransform,
  visibility: noTransform,
  whiteSpace: noTransform,
  width: noTransform,
  zIndex: noTransform,
};

const spacingAliasesMap: Record<SpacingAliases, Spacing | Spacing[]> = {
  m: 'margin',
  marginX: ['marginLeft', 'marginRight'],
  marginY: ['marginTop', 'marginBottom'],
  mb: 'marginBottom',
  ml: 'marginLeft',
  mr: 'marginRight',
  mt: 'marginTop',
  mx: ['marginLeft', 'marginRight'],
  my: ['marginTop', 'marginBottom'],
  p: 'padding',
  paddingX: ['paddingLeft', 'paddingRight'],
  paddingY: ['paddingTop', 'paddingBottom'],
  pb: 'paddingBottom',
  pl: 'paddingLeft',
  pr: 'paddingRight',
  pt: 'paddingTop',
  px: ['paddingLeft', 'paddingRight'],
  py: ['paddingTop', 'paddingBottom'],
};

export { cssPropsMap, DARK, LIGHT, spacingAliasesMap };
